(() => {
  "use strict";
  const $=s=>document.querySelector(s);
  const screens={title:$("#screen-title"),field:$("#screen-field"),hub:$("#screen-hub"),debug:$("#screen-debug"),battle:$("#screen-battle"),clear:$("#screen-clear"),defeat:$("#screen-defeat"),status:null,backpack:null,shop:null};
  const interpreter=new SpellRuntime.SpellInterpreter({stepLimit:1000});
  const partySpecies={sophie:{name:"ソフィー",baseStats:{hp:85,attack:110,defense:80,spAttack:20,spDefense:70,speed:95}},lumiere:{name:"ルミエル",baseStats:{hp:70,attack:10,defense:65,spAttack:125,spDefense:95,speed:75}}};
  const START_LEVEL=8,SPELL_SLOT_COUNT=4,START_MONEY=600;
  const itemDefinitions={
    healPotion:{name:"ヒールポーション",type:"consumable",price:80,healHp:30,description:"仲間1人のHPを30回復する。"},
    manaPotion:{name:"マナポーション",type:"consumable",price:100,healMp:20,description:"仲間1人のMPを20回復する。"},
    powerGrimoire:{name:"力の魔導書",type:"equipment",price:350,stat:"attack",bonus:8,description:"装備中、攻撃が8上がる。"},
    guardGrimoire:{name:"守りの魔導書",type:"equipment",price:350,stat:"defense",bonus:8,description:"装備中、防御が8上がる。"},
    magicGrimoire:{name:"魔力の魔導書",type:"equipment",price:450,stat:"spAttack",bonus:10,description:"装備中、特攻が10上がる。"},
    swiftGrimoire:{name:"迅速の魔導書",type:"equipment",price:400,stat:"speed",bonus:8,description:"装備中、素早さが8上がる。"}
  };
  function calcStat(base,level,isHp=false){const core=Math.floor((2*base*level)/100);return isHp?core+level+10:core+5}
  function calculateStats(baseStats,level){return{hp:calcStat(baseStats.hp,level,true),attack:calcStat(baseStats.attack,level),defense:calcStat(baseStats.defense,level),spAttack:calcStat(baseStats.spAttack,level),spDefense:calcStat(baseStats.spDefense,level),speed:calcStat(baseStats.speed,level)}}
  function maxMpFor(stats,level){return 15+level+Math.floor(stats.spAttack/3)}
  function expToNext(level){return level*20}
  const state={selectedSpellKey:null,drafts:Object.create(null),lastRun:null,registeredSpells:Object.create(null),spellSlots:Array(SPELL_SLOT_COUNT).fill(null),unlockedSpellbooks:{fire:true,repair:false},battle:null,busy:false,pendingActions:{sophie:null,lumiere:null},party:null,money:START_MONEY,inventory:Object.create(null),equipment:{sophie:null,lumiere:null}};
  function equipmentBonus(memberKey){const itemKey=state.equipment?.[memberKey],item=itemDefinitions[itemKey];return item?.type==="equipment"?item:null}
  function getMemberStats(memberKey){const progress=state.party[memberKey],species=partySpecies[memberKey],stats=calculateStats(species.baseStats,progress.level),equip=equipmentBonus(memberKey);if(equip?.stat&&Object.prototype.hasOwnProperty.call(stats,equip.stat))stats[equip.stat]+=equip.bonus||0;return stats}
  function normalizeVitals(memberKey){const p=state.party[memberKey],stats=getMemberStats(memberKey);p.hp=Math.max(0,Math.min(Number.isFinite(p.hp)?p.hp:stats.hp,stats.hp));const maxMp=maxMpFor(stats,p.level);p.mp=Math.max(0,Math.min(Number.isFinite(p.mp)?p.mp:maxMp,maxMp))}
  function resetParty(){state.party={sophie:{level:START_LEVEL,exp:0,hp:null,mp:null},lumiere:{level:START_LEVEL,exp:0,hp:null,mp:null}};normalizeVitals("sophie");normalizeVitals("lumiere")}
  function resetItems(){state.money=START_MONEY;state.inventory=Object.create(null);state.equipment={sophie:null,lumiere:null}}
  function addExp(memberKey,amount){const member=state.party[memberKey];if(!member)return{levels:0,level:0,exp:0};member.exp+=Math.max(0,Math.floor(amount||0));let levels=0;while(member.exp>=expToNext(member.level)){member.exp-=expToNext(member.level);member.level+=1;levels+=1}return{levels,level:member.level,exp:member.exp,next:expToNext(member.level)}}
  function serializeParty(){return JSON.parse(JSON.stringify(state.party))}
  function restoreParty(data){if(!data)return;for(const key of ["sophie","lumiere"]){if(data[key]){state.party[key].level=Math.max(1,Math.floor(data[key].level||START_LEVEL));state.party[key].exp=Math.max(0,Math.floor(data[key].exp||0));state.party[key].hp=Number.isFinite(data[key].hp)?data[key].hp:null;state.party[key].mp=Number.isFinite(data[key].mp)?data[key].mp:null;normalizeVitals(key)}}}
  function serializeItems(){return{money:state.money,inventory:{...state.inventory},equipment:{...state.equipment}}}
  function restoreItems(data){state.money=Math.max(0,Math.floor(data?.money??START_MONEY));state.inventory=Object.assign(Object.create(null),data?.inventory||{});if(Number(data?.inventory?.repairManual||0)>0){state.unlockedSpellbooks.repair=true;delete state.inventory.repairManual;}state.equipment={sophie:null,lumiere:null,...(data?.equipment||{})};for(const key of ["sophie","lumiere"]){if(!itemDefinitions[state.equipment[key]]||itemDefinitions[state.equipment[key]].type!=="equipment")state.equipment[key]=null;}normalizeVitals("sophie");normalizeVitals("lumiere");updateComputer()}
  function inventoryCount(key){return Math.max(0,Math.floor(state.inventory[key]||0))}
  function addItem(key,count=1){if(!itemDefinitions[key])return false;state.inventory[key]=inventoryCount(key)+Math.max(0,Math.floor(count));return true}
  function removeItem(key,count=1){const n=Math.max(0,Math.floor(count));if(inventoryCount(key)<n)return false;state.inventory[key]=inventoryCount(key)-n;if(state.inventory[key]<=0)delete state.inventory[key];return true}
  function buyItem(key){const item=itemDefinitions[key];if(!item||item.price<=0||state.money<item.price)return false;state.money-=item.price;addItem(key,1);return true}
  function equipItem(memberKey,itemKey){const item=itemDefinitions[itemKey];if(!partySpecies[memberKey]||item?.type!=="equipment"||inventoryCount(itemKey)<1)return false;const old=state.equipment[memberKey];removeItem(itemKey,1);if(old)addItem(old,1);state.equipment[memberKey]=itemKey;normalizeVitals(memberKey);return true}
  function unequipItem(memberKey){const old=state.equipment[memberKey];if(!old)return false;addItem(old,1);state.equipment[memberKey]=null;normalizeVitals(memberKey);return true}
  function useItem(memberKey,itemKey){const item=itemDefinitions[itemKey],p=state.party[memberKey];if(!p||item?.type!=="consumable"||inventoryCount(itemKey)<1)return{ok:false,amount:0};const stats=getMemberStats(memberKey);if(item.healHp){const before=p.hp;p.hp=Math.min(stats.hp,p.hp+item.healHp);const amount=p.hp-before;if(amount<=0)return{ok:false,amount:0};removeItem(itemKey,1);return{ok:true,amount}}if(item.healMp){const maxMp=maxMpFor(stats,p.level),before=p.mp;p.mp=Math.min(maxMp,p.mp+item.healMp);const amount=p.mp-before;if(amount<=0)return{ok:false,amount:0};removeItem(itemKey,1);return{ok:true,amount}}return{ok:false,amount:0}}
  resetItems();resetParty();

  const spellDefinitions={
    fire:{name:"Fire",power:60,initialCode:`# Fire：1000回ループではオーバーヒートします。\nspell fire\n\nfor i in range(1000):\n    print(5 - i)\n\ncast("fire")`,hint:'range(1000) を必要な回数まで減らし、5 → 4 → 3 → 2 → 1 と出力してから cast("fire") を実行する。',validate:r=>interpreter.validateFire(r)},
    repair:{name:"Repair",heal:20,initialCode:`# Repair：HPが20未満のときだけ修復魔法を実行する。\nspell repair\n\nhp = 12\n\nif hp < 5:\n    cast("repair")`,hint:'hp は12です。HPが20未満なら Repair を実行するよう、if の条件を直してください。',validate:r=>interpreter.validateRepair(r)}
  };

  function ensureComputerUi(){
    const hub=$("#screen-hub");if(!hub)return;
    hub.classList.add("computer-screen");
    const heading=hub.querySelector(".screen-heading");if(heading){const k=heading.querySelector(".kicker"),h=heading.querySelector("h2");if(k)k.textContent="SOPHIE PC";if(h)h.textContent="パソコン";}
    const grid=hub.querySelector(".spell-grid");if(grid&&!$("#pc-library-note")){const note=document.createElement("div");note.id="pc-library-note";note.className="pc-library-note";note.innerHTML='<strong>GRIMOIRE LIBRARY</strong><span>保存されている魔導書を選び、エディタでコードを解析・修正する。</span>';grid.insertAdjacentElement("beforebegin",note);}
    const cards=grid?.querySelectorAll(".spell-card")||[];
    if(cards[0]){cards[0].dataset.spellbook="fire";cards[0].querySelector(".eyebrow").textContent="GRIMOIRE / LOOP";cards[0].querySelector("h3").textContent="Fire";cards[0].querySelector("p").textContent="最初からPCに保存されている攻撃魔法の魔導書。ループの不具合を直して解析する。";cards[0].querySelector(".spell-spec").innerHTML='<div><dt>効果</dt><dd>威力60</dd></div><div><dt>主題</dt><dd>for / 計算量</dd></div>';const b=cards[0].querySelector("button");if(b){b.id="develop-fire";b.textContent="エディタで開く";}}
    if(cards[1]){cards[1].dataset.spellbook="repair";cards[1].querySelector(".eyebrow").textContent="GRIMOIRE / IF";cards[1].querySelector("h3").textContent="Repair";cards[1].querySelector("p").textContent="パーツ屋の端末から入手できる修復魔法の魔導書。条件分岐を直して解析する。";cards[1].querySelector(".spell-spec").innerHTML='<div><dt>効果</dt><dd>HPを20修復</dd></div><div><dt>主題</dt><dd>変数 / if</dd></div>';const s=cards[1].querySelector(".badge");if(s)s.id="repair-status";const b=cards[1].querySelector("button");if(b){b.id="develop-repair";b.textContent="エディタで開く";}}
    const deploy=hub.querySelector(".deploy-panel");if(deploy){deploy.querySelector(".eyebrow").textContent="LOG OUT";deploy.querySelector("h3").textContent="パソコンを閉じる";deploy.querySelector("p").textContent="編集内容は下書きとして保存されます。解析済みの魔法は実戦登録枠へセットできます。";const b=deploy.querySelector("button");if(b)b.textContent="フィールドへ戻る";}
    const debug=$("#screen-debug");if(debug){debug.classList.add("computer-editor-screen");const k=debug.querySelector(".kicker");if(k)k.textContent="CODE EDITOR";const back=$("#back-workshop");if(back)back.textContent="パソコンへ戻る";const manual=debug.querySelector(".manual h4");if(manual)manual.textContent="エディタで使える命令";}
  }

  function showScreen(name){Object.values(screens).filter(Boolean).forEach(el=>el.classList.remove("active"));screens[name]?.classList.add("active")}
  function isSpellEquipped(key){return state.spellSlots.includes(key)}
  function getEquippedSpell(key){return isSpellEquipped(key)?state.registeredSpells[key]||null:null}
  function isSpellbookUnlocked(key){return Boolean(state.unlockedSpellbooks[key])}
  function unlockSpellbook(key){if(!spellDefinitions[key])return false;state.unlockedSpellbooks[key]=true;updateComputer();return true}
  function equipSpell(key,preferredIndex=null){if(!state.registeredSpells[key])return false;if(isSpellEquipped(key))return true;let index=Number.isInteger(preferredIndex)&&preferredIndex>=0&&preferredIndex<SPELL_SLOT_COUNT&&!state.spellSlots[preferredIndex]?preferredIndex:state.spellSlots.findIndex(v=>!v);if(index<0)return false;state.spellSlots[index]=key;window.SpellMenu?.renderLoadout?.();return true}
  function unequipSlot(index){if(!Number.isInteger(index)||index<0||index>=SPELL_SLOT_COUNT)return false;state.spellSlots[index]=null;window.SpellMenu?.renderLoadout?.();updateComputer();return true}
  function magicReady(){return Boolean(getEquippedSpell("fire")&&getEquippedSpell("repair"))}
  function setRunState(label,style){const el=$("#run-state");if(el){el.textContent=label;el.className=`status ${style}`}}
  function resetAll(){state.selectedSpellKey=null;state.drafts=Object.create(null);state.lastRun=null;state.registeredSpells=Object.create(null);state.spellSlots=Array(SPELL_SLOT_COUNT).fill(null);state.unlockedSpellbooks={fire:true,repair:false};state.battle=null;state.busy=false;state.pendingActions={sophie:null,lumiere:null};resetItems();resetParty();updateComputer()}
  function updateComputer(){ensureComputerUi();const available=["fire","repair"].filter(isSpellbookUnlocked),solved=available.filter(k=>state.registeredSpells[k]).length;const progress=$("#workshop-progress");if(progress){progress.textContent=`${solved} / ${available.length} 解析済み`;progress.className=`badge ${available.length&&solved===available.length?"success":"muted"}`;}for(const key of ["fire","repair"]){const badge=$(`#${key}-status`),spell=state.registeredSpells[key],unlocked=isSpellbookUnlocked(key),card=document.querySelector(`[data-spellbook="${key}"]`),button=card?.querySelector("button");if(badge){badge.textContent=!unlocked?"未保存":spell?`${isSpellEquipped(key)?"実戦登録中":"解析済み"} / MP ${spell.mpCost}`:"未解析";badge.className=spell?"badge success":"badge muted";}if(card)card.classList.toggle("locked",!unlocked);if(button){button.disabled=!unlocked;button.textContent=unlocked?"エディタで開く":"未保存";}}window.SpellMenu?.renderLoadout?.();window.SpellField?.updateObjective?.()}
  function openComputer(){updateComputer();showScreen("hub")}
  function openWorkshop(){openComputer()}
  function resetDebugResult(){state.lastRun=null;$("#register-spell").disabled=true;const key=state.selectedSpellKey,reg=key?state.registeredSpells[key]:null;$("#spell-badge").textContent=reg?`${spellDefinitions[key].name} 解析済み / MP ${reg.mpCost}`:"未解析";$("#spell-badge").className=reg?"badge success":"badge muted";setRunState("READY","neutral");$("#console-output").textContent="コードを実行してください。";$("#metric-steps").textContent="—";$("#metric-mp").textContent="—";$("#metric-result").textContent="未実行"}
  function openDebug(key){if(!isSpellbookUnlocked(key))return;state.selectedSpellKey=key;state.lastRun=null;const def=spellDefinitions[key];$("#debug-title").textContent=`エディタ：${def.name}`;$("#debug-hint").textContent=def.hint;$("#code-editor").value=state.drafts[key]??def.initialCode;resetDebugResult();showScreen("debug")}
  function resetCode(){const key=state.selectedSpellKey;if(!key)return;state.drafts[key]=spellDefinitions[key].initialCode;$("#code-editor").value=state.drafts[key];resetDebugResult()}
  function ngMessages(key,v){const c=v.checks||{},a=[];if(key==="fire"){if(!c.spellMatches)a.push("- `spell fire` が必要です。");if(!c.loopUsed)a.push("- `for` ループを使ってください。");if(!c.outputMatches)a.push("- 出力を 5,4,3,2,1 にしてください。");if(!c.castMatches)a.push('- `cast("fire")` を1回実行してください。')}else{if(!c.spellMatches)a.push("- `spell repair` が必要です。");if(!c.assignmentUsed)a.push("- HPを変数へ代入してください。");if(!c.conditionalUsed)a.push("- `if` 条件分岐を使ってください。");if(!c.castMatches)a.push('- 条件成立時に `cast("repair")` を1回実行してください。')}return a}
  function runCode(){const key=state.selectedSpellKey;if(!key)return;const source=$("#code-editor").value;state.drafts[key]=source;try{const result=interpreter.run(source),validation=spellDefinitions[key].validate(result);state.lastRun={...result,validation,key,source};const lines=result.output.map(v=>`> ${v}`);result.casts.forEach(s=>lines.push(`[CAST] ${s.toUpperCase()}`));if(!lines.length)lines.push("(出力なし)");lines.push("",`実行ステップ: ${result.steps}`,`推定MP: ${result.mpCost}`);if(validation.ok){lines.push("",`CHECK OK: ${spellDefinitions[key].name} の解析に成功しました。`);setRunState("SUCCESS","good");$("#metric-result").textContent="成功";$("#register-spell").disabled=false}else{lines.push("","CHECK NG:",...ngMessages(key,validation));setRunState("CHECK NG","warn");$("#metric-result").textContent="条件未達";$("#register-spell").disabled=true}$("#console-output").textContent=lines.join("\n");$("#metric-steps").textContent=result.steps;$("#metric-mp").textContent=result.mpCost}catch(e){state.lastRun=null;$("#register-spell").disabled=true;const hot=e instanceof SpellRuntime.OverheatError;setRunState(hot?"OVERHEAT":"ERROR","bad");$("#console-output").textContent=hot?`${e.name}: ${e.message}\n\nヒント: ループ回数を減らして再実行してください。`:`${e.name}: ${e.message}`;$("#metric-steps").textContent=hot?">1000":"—";$("#metric-mp").textContent="—";$("#metric-result").textContent=hot?"過熱停止":"エラー"}}
  function registerSpell(){if(!state.lastRun?.validation?.ok)return;const key=state.lastRun.key,def=spellDefinitions[key];state.registeredSpells[key]={key,name:def.name,mpCost:state.lastRun.mpCost,steps:state.lastRun.steps,power:def.power||0,heal:def.heal||0,source:state.lastRun.source};equipSpell(key);openComputer()}
  function serializeMagic(){return{drafts:{...state.drafts},registeredSpells:JSON.parse(JSON.stringify(state.registeredSpells)),spellSlots:[...state.spellSlots],unlockedSpellbooks:{...state.unlockedSpellbooks}}}
  function restoreMagic(data){
    const drafts={...(data?.drafts||{})};if(drafts.heal&&!drafts.repair)drafts.repair=String(drafts.heal).replace(/heal/g,"repair");delete drafts.heal;state.drafts=Object.assign(Object.create(null),drafts);
    const registered=JSON.parse(JSON.stringify(data?.registeredSpells||{}));if(registered.heal&&!registered.repair){registered.repair={...registered.heal,key:"repair",name:"Repair",source:String(registered.heal.source||"").replace(/heal/g,"repair")};}delete registered.heal;state.registeredSpells=Object.assign(Object.create(null),registered);
    state.unlockedSpellbooks={fire:true,repair:Boolean(data?.unlockedSpellbooks?.repair||registered.repair)};
    state.spellSlots=Array(SPELL_SLOT_COUNT).fill(null);if(Array.isArray(data?.spellSlots)){for(let i=0;i<SPELL_SLOT_COUNT;i++){let key=data.spellSlots[i];if(key==="heal")key="repair";if(key&&state.registeredSpells[key]&&!state.spellSlots.includes(key))state.spellSlots[i]=key}}else{Object.keys(state.registeredSpells).slice(0,SPELL_SLOT_COUNT).forEach((key,i)=>state.spellSlots[i]=key)}updateComputer();
  }

  ensureComputerUi();
  window.SpellGame03={$,screens,state,interpreter,spellDefinitions,partySpecies,itemDefinitions,START_LEVEL,SPELL_SLOT_COUNT,START_MONEY,calculateStats,getMemberStats,maxMpFor,expToNext,addExp,serializeParty,restoreParty,serializeItems,restoreItems,inventoryCount,addItem,removeItem,buyItem,equipItem,unequipItem,useItem,isSpellEquipped,getEquippedSpell,equipSpell,unequipSlot,isSpellbookUnlocked,unlockSpellbook,showScreen,openComputer,openWorkshop,updateComputer,updateWorkshop:updateComputer,magicReady,serializeMagic,restoreMagic,normalizeVitals};
  $("#start-button").addEventListener("click",()=>{resetAll();window.SpellField?.startNewGame()});
  $("#develop-fire").addEventListener("click",()=>openDebug("fire"));$("#develop-repair").addEventListener("click",()=>openDebug("repair"));$("#reset-code").addEventListener("click",resetCode);$("#run-code").addEventListener("click",runCode);$("#register-spell").addEventListener("click",registerSpell);$("#back-workshop").addEventListener("click",()=>{if(state.selectedSpellKey)state.drafts[state.selectedSpellKey]=$("#code-editor").value;openComputer()});$("#return-field").addEventListener("click",()=>window.SpellField?.returnFromWorkshop());
  resetAll();
})();
