(() => {
  "use strict";
  const G=window.SpellGame03,$=G.$,state=G.state,delay=ms=>new Promise(r=>setTimeout(r,ms));
  const enemyTemplate={name:"グリッチスライム",maxHp:90,attack:10,symbol:"●"};
  let lastStart=null; const log=t=>$("#battle-log").textContent=t;
  function menu(name){["#sophie-menu","#lumiere-menu","#magic-menu","#heal-target-menu"].forEach(id=>$(id).classList.add("hidden"));if(name==="sophie")$("#sophie-menu").classList.remove("hidden");if(name==="lumiere")$("#lumiere-menu").classList.remove("hidden");if(name==="magic")$("#magic-menu").classList.remove("hidden");if(name==="heal")$("#heal-target-menu").classList.remove("hidden")}
  function bar(b,t,v,m){v=Math.max(0,v);$(b).style.width=`${Math.max(0,Math.min(100,v/m*100))}%`;$(t).textContent=`${v}/${m}`}
  function render(){const b=state.battle;if(!b)return;bar("#enemy-hp-bar","#enemy-hp-text",b.enemy.hp,b.enemy.maxHp);bar("#sophie-hp-bar","#sophie-hp-text",b.sophie.hp,b.sophie.maxHp);bar("#lumiere-hp-bar","#lumiere-hp-text",b.lumiere.hp,b.lumiere.maxHp);bar("#lumiere-mp-bar","#lumiere-mp-text",b.lumiere.mp,b.lumiere.maxMp)}
  function anim(sel,cls){const el=$(sel);el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),650)}
  function startFieldBattle(){if(!G.magicReady()){window.SpellField?.showDialog("ルミエル「まだ実戦用の魔法が揃ってない。先に工房へ行こう。」");return false}lastStart="field";state.battle={enemy:{...enemyTemplate,hp:enemyTemplate.maxHp},sophie:{hp:42,maxHp:42},lumiere:{hp:35,maxHp:35,mp:30,maxMp:30},defend:{sophie:false,lumiere:false}};state.pendingActions={sophie:null,lumiere:null};state.busy=false;$("#enemy-name").textContent=state.battle.enemy.name;$("#enemy-sprite").textContent=state.battle.enemy.symbol;$("#fire-cost").textContent=`MP ${state.registeredSpells.fire.mpCost}`;$("#heal-cost").textContent=`MP ${state.registeredSpells.heal.mpCost}`;log(`${state.battle.enemy.name}が あらわれた！\nソフィーはどうする？`);menu("sophie");render();G.showScreen("battle");return true}
  function sophie(action){if(state.busy)return;state.pendingActions.sophie=action;log(`ソフィー：${action==="fight"?"たたかう":"ぼうぎょ"}\nルミエルはどうする？`);menu("lumiere")}
  function lumiere(action){if(state.busy)return;if(action==="magic"){log("ルミエルはどの魔法を使う？");menu("magic");return}state.pendingActions.lumiere={type:action};round()}
  function mpCheck(spell){if(state.battle.lumiere.mp>=spell.mpCost)return true;log("MPが足りない！\nルミエルは別の行動を選んでください。");menu("lumiere");return false}
  function fire(){if(state.busy||!mpCheck(state.registeredSpells.fire))return;state.pendingActions.lumiere={type:"fire"};round()}
  function heal(){if(state.busy||!mpCheck(state.registeredSpells.heal))return;log("Healの対象を選んでください。");menu("heal")}
  function healTarget(target){if(!state.busy){state.pendingActions.lumiere={type:"heal",target};round()}}
  async function enemyTurn(){const b=state.battle,target=Math.random()<.5?"sophie":"lumiere",dmg=b.defend[target]?Math.ceil(b.enemy.attack/2):b.enemy.attack;b[target].hp-=dmg;anim(target==="sophie"?".sophie-battle":".lumiere-battle","hit");log(`${b.enemy.name}の こうげき！\n${target==="sophie"?"ソフィー":"ルミエル"}は ${dmg} のダメージをうけた。`);render();await delay(560)}
  async function win(){state.busy=false;$("#clear-fire-mp").textContent=state.registeredSpells.fire.mpCost;$("#clear-heal-mp").textContent=state.registeredSpells.heal.mpCost;G.showScreen("clear")}
  async function round(){if(state.busy||!state.battle)return;state.busy=true;const b=state.battle,la=state.pendingActions.lumiere;b.defend.sophie=state.pendingActions.sophie==="defend";b.defend.lumiere=la?.type==="defend";menu("none");if(state.pendingActions.sophie==="fight"){b.enemy.hp-=12;anim(".sophie-battle","cast");anim("#enemy-sprite","hit");log(`ソフィーの こうげき！\n${b.enemy.name}に 12 のダメージ！`);render();await delay(500);if(b.enemy.hp<=0)return win()}else{log("ソフィーは みをまもっている。");await delay(320)}if(la?.type==="fire"){const s=state.registeredSpells.fire;b.lumiere.mp-=s.mpCost;b.enemy.hp-=s.damage;anim(".lumiere-battle","cast");anim("#enemy-sprite","hit");log(`ルミエルは 自作魔法 Fire を実行した！\n${b.enemy.name}に ${s.damage} のダメージ！\nMP ${s.mpCost} 消費（${s.steps} steps）。`);render();await delay(600);if(b.enemy.hp<=0)return win()}else if(la?.type==="heal"){const s=state.registeredSpells.heal,t=b[la.target],before=t.hp;t.hp=Math.min(t.maxHp,t.hp+s.heal);b.lumiere.mp-=s.mpCost;anim(".lumiere-battle","cast");log(`ルミエルは 自作魔法 Heal を実行した！\n${la.target==="sophie"?"ソフィー":"ルミエル"}のHPが ${t.hp-before} 回復した。\nMP ${s.mpCost} 消費（${s.steps} steps）。`);render();await delay(600)}else{log("ルミエルは みをまもっている。");await delay(320)}await enemyTurn();if(b.sophie.hp<=0||b.lumiere.hp<=0){state.busy=false;G.showScreen("defeat");return}state.pendingActions={sophie:null,lumiere:null};state.busy=false;log("次のターン。\nソフィーはどうする？");menu("sophie")}
  $("#sophie-fight").addEventListener("click",()=>sophie("fight"));$("#sophie-defend").addEventListener("click",()=>sophie("defend"));$("#lumiere-magic").addEventListener("click",()=>lumiere("magic"));$("#lumiere-defend").addEventListener("click",()=>lumiere("defend"));$("#cast-fire").addEventListener("click",fire);$("#cast-heal").addEventListener("click",heal);$("#magic-back").addEventListener("click",()=>{log("ルミエルはどうする？");menu("lumiere")});$("#heal-sophie").addEventListener("click",()=>healTarget("sophie"));$("#heal-lumiere").addEventListener("click",()=>healTarget("lumiere"));$("#heal-back").addEventListener("click",()=>{log("ルミエルはどの魔法を使う？");menu("magic")});$("#retry-battle").addEventListener("click",()=>{if(lastStart==="field")startFieldBattle()});$("#defeat-workshop").addEventListener("click",G.openWorkshop);$("#clear-field").addEventListener("click",()=>window.SpellField?.onBattleWon());
  G.startFieldBattle=startFieldBattle;
})();
